config/routes.rb
SnailNet::Application.routes.draw do
  resources :data

  resources :messages

  authenticated :user do
    root :to    => 'home#index'
  end

  
  root :to      => "home#index"

  match "data"  => "index#fetch_data"

  devise_for :users
  resources :users, :only => [:show, :index]
end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :body, :published
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @messages }
    end
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    @message = Message.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/new
  # GET /messages/new.json
  def new
    @message = Message.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/1/edit
  def edit
    @message = Message.find(params[:id])
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(params[:message])

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render json: @message, status: :created, location: @message }
      else
        format.html { render action: "new" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /messages/1
  # PUT /messages/1.json
  def update
    @message = Message.find(params[:id])

    respond_to do |format|
      if @message.update_attributes(params[:message])
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message = Message.find(params[:id])
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<div id='app'>
  <div class="container">
    <div class="row-fluid">
      <div class="span12 text-center" style="padding-top: 50px;">
        <%= form_for @message do |f| %>
          <fieldset>
            <legend>Edit Message of the Day</legend>
            <div class="controls">
              <%= f.text_area :body, :class => "field span12" %><br />
            </div>
          <%= f.submit %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/messages/edit.html.erb
<div id='app'>
  <div class="container">
    <div class="row-fluid">
      <div class="span12 text-center" style="padding-top: 50px;">
        <p id="notice"><%= notice %></p>
          <h1>Editing message</h1>

          <%= render 'form' %>

          <%= link_to 'Show', @message %> |
          <%= link_to 'Back', messages_path %>
      </div>
    </div>
  </div>
</div>

app/views/messages/index.html.erb
<div id='app'>
  <div class="container">
    <div class="row-fluid">
      <div class="span12 text-center" style="padding-top: 50px;">
        <h1>Listing messages</h1>

        <table>
          <tr>
            <th>Body</th>
            <th>Published</th>
            <th></th>
            <th></th>
            <th></th>
          </tr>

        <% @messages.each do |message| %>
          <tr>
            <td><%= message.body %></td>
            <td><%= message.published %></td>
            <td><%= link_to 'Show', message %></td>
            <td><%= link_to 'Edit', edit_message_path(message) %></td>
            <td><%= link_to 'Destroy', message, confirm: 'Are you sure?', method: :delete %></td>
          </tr>
        <% end %>
        </table>

        <br />

        <%= link_to 'New Message', new_message_path %>
      </div>
    </div>
  </div>
</div>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<div id='app'>
  <div class="container">
    <div class="row-fluid">
      <div class="span12 text-center" style="padding-top: 50px;">
        <p id="notice"><%= notice %></p>

        <p>
          <b>Body:</b>
          <%= @message.body %>
        </p>

        <p>
          <b>Published:</b>
          <%= @message.published %>
        </p>
        <%= link_to 'Edit', edit_message_path(@message) %> |
        <%= link_to 'Back', messages_path %>
      </div>
    </div>
  </div>
</div>