config/routes.rb
SnailNet::Application.routes.draw do
  resources :data

  resources :messages

  authenticated :user do
    root :to    => 'home#index'
  end

  
  root :to      => "home#index"

  match "data"  => "index#fetch_data"

  devise_for :users
  resources :users, :only => [:show, :index]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.find(:all, :select => 'name, score' )
    @message = Message.first
    #@chair_1_current = 
    #@chair_2_current
    #@chair_3_current
    #@chair_4_current

    @chair_1_total = Datum.where( :chair => 1).all
    @chair_2_total = Datum.where( :chair => 2).all
    @chair_3_total = Datum.where( :chair => 3).all
    @chair_4_total = Datum.where( :chair => 4).all
    #self.fetch_data
  end

  def fetch_data
    #params for serial port
    #port_str = "/dev/tty.usbserial"  #may be different
    port_str = "/dev/tty.usbserial-A6004agj"  #may be different
    baud_rate = 9600
    data_bits = 8
    stop_bits = 1
    parity = SerialPort::NONE

    sp = SerialPort.new(port_str, baud_rate, data_bits, stop_bits, parity)

    Thread.new do
      while true do
        Rails.logger.info Time.now # or call tick function
        sleep 1
      end
    end
    #just read forever to find how to terminate
    while false do
      Rails.logger.info 'READING'
      while (i = sp.gets.chomp) do       # see note 2
        Rails.logger.info '-----------------------------------'
        Rails.logger.info i.inspect
        #puts i.class #String
      end
    end
    sp.close
  end

  def avatar_url(user)  
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    "http://gravatar.com/avatar/#{gravatar_id}.png"
  end 
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div id='app'>
  <div class="home">
    <div id="userNotLoggedIn">
      <div class="container">
          <div class="row-fluid stoolGagues" style="padding-bottom: 50px;">
            <div class="chartDiv1 span3"><div id="chartDiv1" style="width: 300px; height:150px;"></div></div>
            <div class="chartDiv2 span3"><div id="chartDiv2" style="width: 300px; height:150px;"></div></div>
            <div class="chartDiv3 span3"><div id="chartDiv3" style="width: 300px; height:150px;"></div></div>
            <div class="chartDiv4 span3"><div id="chartDiv4" style="width: 300px; height:150px;"></div></div>
          </div>
        <div>
        <div class="paginationButtons container">
            <div class="row-fluid" >
              <div class="span12" style="text-align:center; margin-top:-75px;">
                <button class="pageForwardBtn btn">&#8592;</button>
                &nbsp;&nbsp;&nbsp;
                <button class="mobileLoginBtn btn">Login</button>
                &nbsp;&nbsp;&nbsp;
                <button class="pageBackBtn btn">&#8594;</button>
              </div>
            </div>
            <div class="row-fluid" >
              <div class="span12" style="text-align:center; margin-top:-75px;">
              </div>
            </div>
          </div>
        </div>
        <!-- <div class="container">
        <div class="row-fluid stoolGaguesMobile" style="padding-bottom: 50px;">
          <div class="span12">
            <div class="bxSlider">
              <div id="chartDiv1mobile" style="width: 300px; height:150px;">wat</div>
              <div id="chartDiv2mobile" style="width: 300px; height:150px;">wat</div>
              <div id="chartDiv3mobile" style="width: 300px; height:150px;">wat</div>
              <div id="chartDiv4mobile" style="width: 300px; height:150px;">wat</div>
            </div>
          </div>
        </div> -->
        <div class="container">
          <div class="row-fluid">
            <div class="span12">
              <div class="row-fluid">
                <div class="span4">
                  <div id="newsletter" style="padding-right:25px;">
                    <p><%= @message.body.html_safe %></p>
                  </div>
                </div>
                <div class="span4">
                  <div id="loginForm">
                  <%= form_for("user", :url => user_session_path, :html => {:class => "form-vertical"}) do |f| %>
                    <fieldset>
                      <div class="control-group">
                        <label class="control-label" for="user_email">Email</label>
                        <div class="controls"><%= f.text_field :email, :placeholder => "Email" %></div>
                      </div>
                      <div class="control-group">
                        <label class="control-label" for="user_password">Password</label>
                        <div class="controls">
                          <%= f.password_field :password, :placeholder => "Password" %>
                        </div>
                      <div class="control-group">
                        <%= f.label :remember_me, :class => 'control-label' %>
                        <div class="controls"><%= f.check_box :remember_me, :style => "margin-top: 0px;" %></div>
                      </div>
                      <div class="form-actions" ><%= f.submit 'Sign in', :class => 'btn btn-primary' %>
                      <%= link_to 'Register', new_user_registration_path, :class => 'btn', :style => 'margin-left: 20px;' %> </div>
                      <%= link_to "Forgot your password?", new_password_path('user') %>
          </div>
                    </fieldset>
                  <% end %>
                </div>
                </div>
                <div class="span4">
                  <div class='newsletter'>
                  <%= form_for("user", :url => user_session_path, :html => {:class => "form-vertical"}) do |f| %>
                    <fieldset>
                      <div class="control-group">
                        <label class="control-label" for="user_email">Snailnet Newsletter</label>
                        <div class="controls"><%= f.text_field :email, :placeholder => "Sign Up!" %></div>
                      </div>
                      <div class="control-group">
                        <div class="form-actions" >
                          <%= f.submit 'Sign Up', :class => 'btn btn-primary' %>
                        </div>
                      </div>
                    </fieldset>
                  <% end %>
                </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div> <!-- id="userNotLoggedIn" -->

    <div id="userLoggedIn">
      <div id="leaderboard" class="container row-fluid">
        <div class="span12 userView">
          <div class="allGagues container">
              <div class="row-fluid stoolGagues" style="padding-bottom: 50px;">
                <div class="span3"><div id="chartDiv1Leaderboard" style="width: 173px; height:150px;"></div></div>
                <div class="span3"><div id="chartDiv2Leaderboard" style="width: 173px; height:150px;"></div></div>
                <div class="span3"><div id="chartDiv3Leaderboard" style="width: 173px; height:150px;"></div></div>
                <div class="span3"><div id="chartDiv4Leaderboard" style="width: 173px; height:150px;"></div></div>
              </div>
            </div>

              <div class="span12 userView" style="text-aligin:center;">
                <h2 id="userChairLabel" style="padding-bottom:25px;">Where are you?</h2>
                <div id="chartDivUser" style="" ></div>
              </div>
          </div>
        </div>
      <div class="container row-fluid">
        <div class="span12" style="text-align:center;">
          <div class="span4">
            <h3 style="padding-bottom:25px;">Select where you are</h3>
            <button id="chair1_select" value='0' type="button" class="btn">One</button>
            <button id="chair2_select" value='1' type="button" class="btn">Two</button>
            <button id="chair3_select" value='2' type="button" class="btn">Three</button>
            <button id="chair4_select" value='3' type="button" class="btn">Four</button>
          </div>
          <div class="span4">
          </div>
          <div class="span4">
            <div style="padding-top:50px;">
              <button class='btn' id="viewToggle">Toggle View</button>
          </div>
          </div>
        </div>
      </div>
      </div> <!-- userLoggedIn -->
  </div>
</div>

<%= javascript_tag do %>
  $( document ).ready(function() {
    <% if user_signed_in? %>
      $('#userNotLoggedIn').hide();
      $('#userLoggedIn').fadeIn();
    <% else %>
      $('#userLoggedIn').hide();
      $('#userNotLoggedIn').fadeIn();
    <% end %>
  });
<% end %>