config/routes.rb
SnailNet::Application.routes.draw do
  resources :data

  resources :messages

  authenticated :user do
    root :to    => 'home#index'
  end

  
  root :to      => "home#index"

  match "data"  => "index#fetch_data"

  devise_for :users
  resources :users, :only => [:show, :index]
end

app/controllers/data_controller.rb
class DataController < ApplicationController
  # GET /data
  # GET /data.json
  def index
    @data = Datum.all
    @chair_1 = Datum.where( :chair => 1).all
    @chair_2 = Datum.where( :chair => 2 ).all
    @chair_3 = Datum.where( :chair => 3 ).all
    @chair_4 = Datum.where( :chair => 4 ).all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => {
          :all_data => @data,
          :chair_1 => @chair_1.last,
          :chair_2 => @chair_2,
          :chair_3 => @chair_3.last,
          :chair_4 => @chair_4.last
        }
      }
    end
  end

  # GET /data/1
  # GET /data/1.json
  def show
    @datum = Datum.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @datum }
    end
  end

  # GET /data/new
  # GET /data/new.json
  def new
    # @chair_1_data where
    # @chair_2_data
    # @chair_3_data
    @datum = Datum.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @datum }
    end
  end

  # GET /data/1/edit
  def edit
    @datum = Datum.find(params[:id])
  end

  # POST /data
  # POST /data.json
  def create
    @datum = Datum.new(params[:datum])

    respond_to do |format|
      if @datum.save
        format.html { redirect_to @datum, notice: 'Datum was successfully created.' }
        format.json { render json: @datum, status: :created, location: @datum }
      else
        format.html { render action: "new" }
        format.json { render json: @datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /data/1
  # PUT /data/1.json
  def update
    @datum = Datum.find(params[:id])

    respond_to do |format|
      if @datum.update_attributes(params[:datum])
        format.html { redirect_to @datum, notice: 'Datum was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /data/1
  # DELETE /data/1.json
  def destroy
    @datum = Datum.find(params[:id])
    @datum.destroy

    respond_to do |format|
      format.html { redirect_to data_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/data_helper.rb
module DataHelper
end

app/views/data/_form.html.erb
<%= simple_form_for(@datum) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :chair %>
    <%= f.input :value %>
    <%= f.input :user %>
    <%= f.input :timestamp %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/data/edit.html.erb
<h1>Editing datum</h1>

<%= render 'form' %>

<%= link_to 'Show', @datum %> |
<%= link_to 'Back', data_path %>

app/views/data/index.html.erb
<h1>Listing data</h1>

<table>
  <tr>
    <th>Chair</th>
    <th>Value</th>
    <th>User</th>
    <th>Timestamp</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @data.each do |datum| %>
  <tr>
    <td><%= datum.chair %></td>
    <td><%= datum.value %></td>
    <td><%= datum.user %></td>
    <td><%= datum.timestamp %></td>
    <td><%= link_to 'Show', datum %></td>
    <td><%= link_to 'Edit', edit_datum_path(datum) %></td>
    <td><%= link_to 'Destroy', datum, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Datum', new_datum_path %>

app/views/data/new.html.erb
<h1>New datum</h1>

<%= render 'form' %>

<%= link_to 'Back', data_path %>

app/views/data/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Chair:</b>
  <%= @datum.chair %>
</p>

<p>
  <b>Value:</b>
  <%= @datum.value %>
</p>

<p>
  <b>User:</b>
  <%= @datum.user %>
</p>

<p>
  <b>Timestamp:</b>
  <%= @datum.timestamp %>
</p>


<%= link_to 'Edit', edit_datum_path(@datum) %> |
<%= link_to 'Back', data_path %>