config/routes.rb
SnailNet::Application.routes.draw do
  resources :data

  resources :messages

  authenticated :user do
    root :to    => 'home#index'
  end

  
  root :to      => "home#index"

  match "data"  => "index#fetch_data"

  devise_for :users
  resources :users, :only => [:show, :index]
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">×</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Wilder Snail", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>        
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', new_user_session_path %>  
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Edit account', edit_user_registration_path %>
    </li>
    <% if current_user.has_role? :admin %>
      <li>
      <%= link_to 'Admin', users_path %>
      </li>
    <% end %>
  <% else %>
    <li>
    <%= link_to 'Sign up', new_user_registration_path %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "SnailNet" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    "application", :media => "all", :debug => true %>
    <%= javascript_include_tag "application", :debug => true %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <header>
                <div class="container row">
                  <div class='span12'>
                  </div>
                  <div id="main" class="span12 text-center">
                    <div id="sub" class="span3 text-right">
                      <h2 class="subheader" style="text-align:right; padding-right: 15px; float:right; display:inline;">Home</h2>
                    </div>
                    <h1 style="display:inline;"><%= link_to 'SnailNet', root_path %></h1>
                  </div>
                </div>
                </div>
              </header>
              <div class="row-fluid">
                <div class="span12" style="padding-top:50px;padding-left:30px;">
                  <%= render 'layouts/messages' %>
                </div>
              </div>
              <%= yield %>
              <footer style="padding-top:50px;">
                <div class="footer">
                <div class="container row-fluid">
                  <div class="span3">
                    Copyright 2013 Wilder Snail
                  </div>
                  <div class="span3">
                    <!-- About Us -->
                  </div>
                  <div class="span3">
                    <!-- What is SnailNet? -->
                  </div>
                  <div class="span3">
                    Open Source
                  </div> 
                </div>
              </div>
            </footer>
            </div>
          </div>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>